spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

app.mail.from=${MAIL_FROM}
app.password-reset.url=${PASSWORD_RESET_URL}
app.locale=${APP_LOCALE:en}

# JPA / Hibernate beállítások
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true